sudo: required
services:
  - docker

before_install:
  - docker build -t annamalunina/dockerfrontend -f Dockerfile.dev .

script:
  - docker run annamalunina/dockerfrontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockerfrontend"
  env: "Dockerfrontend-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-215807299913"
  bucket_path: "dockerfrontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"